SUBSCRIPTION_REMINDER_1_TIME = 5
SUBSCRIPTION_REMINDER_2_TIME = 15
LESSON_MESSAGE_1_AUTO_TIME = 15
LESSON_MESSAGE_2_AUTO_TIME = 20
LESSON_MESSAGE_3_AUTO_TIME = 10
WEBINAR_REMINDER_0_AUTO_TIME = 5
WEBINAR_REMINDER_1_AUTO_TIME_FIXED = '23:59'
WEBINAR_REMINDER_3_TIME = 60 * 2
WEBINAR_REMINDER_4_TIME = 60 * 3
WEBINAR_REMINDER_5_TIME = 45
WEBINAR_REMINDER_6_TIME = 15
WEBINAR_REMINDER_7_TIME = 15
WEBINAR_REMINDER_8_TIME = 15
WEBINAR_REMINDER_9_TIME = 15
WEBINAR_REMINDER_10_TIME = 60 * 13
QUESTION_MESSAGE_1_TIME = 30
RESTART_WEBINAR_MESSAGES_TIME = 60 * 20
FIRST_OFFER_MESSAGE_1_TIME = 30
FIRST_OFFER_MESSAGE_2_TIME = 60 * 24
FIRST_OFFER_MESSAGE_3_TIME = 60  * 23
QUESTION_MESSAGE_2_TIME = (60 * 24 * 4) - (60 * 4) # 3 days and 20 hours
FINAL_OFFER_MESSAGE_1_TIME = 60 * 24
FINAL_OFFER_MESSAGE_2_TIME = 60 * 20

def test_mode():
    global SUBSCRIPTION_REMINDER_1_TIME
    global SUBSCRIPTION_REMINDER_2_TIME
    global LESSON_MESSAGE_1_AUTO_TIME
    global LESSON_MESSAGE_2_AUTO_TIME
    global LESSON_MESSAGE_3_AUTO_TIME
    global WEBINAR_REMINDER_0_AUTO_TIME
    global WEBINAR_REMINDER_1_AUTO_TIME_FIXED
    global WEBINAR_REMINDER_3_TIME
    global WEBINAR_REMINDER_4_TIME
    global WEBINAR_REMINDER_5_TIME
    global WEBINAR_REMINDER_6_TIME
    global WEBINAR_REMINDER_7_TIME
    global WEBINAR_REMINDER_8_TIME
    global WEBINAR_REMINDER_9_TIME
    global WEBINAR_REMINDER_10_TIME
    global QUESTION_MESSAGE_1_TIME
    global RESTART_WEBINAR_MESSAGES_TIME
    global FIRST_OFFER_MESSAGE_1_TIME
    global FIRST_OFFER_MESSAGE_2_TIME
    global FIRST_OFFER_MESSAGE_3_TIME
    global QUESTION_MESSAGE_2_TIME  # 3 days and 20 hours
    global FINAL_OFFER_MESSAGE_1_TIME
    global FINAL_OFFER_MESSAGE_2_TIME

    SUBSCRIPTION_REMINDER_1_TIME = 1
    SUBSCRIPTION_REMINDER_2_TIME = 1
    LESSON_MESSAGE_1_AUTO_TIME = 1
    LESSON_MESSAGE_2_AUTO_TIME = 1
    LESSON_MESSAGE_3_AUTO_TIME = 1
    WEBINAR_REMINDER_0_AUTO_TIME = 1
    WEBINAR_REMINDER_1_AUTO_TIME_FIXED = '23:59'
    WEBINAR_REMINDER_3_TIME = 1
    WEBINAR_REMINDER_4_TIME = 1
    WEBINAR_REMINDER_5_TIME = 1
    WEBINAR_REMINDER_6_TIME = 1
    WEBINAR_REMINDER_7_TIME = 1
    WEBINAR_REMINDER_8_TIME = 1
    WEBINAR_REMINDER_9_TIME = 1
    WEBINAR_REMINDER_10_TIME = 1
    QUESTION_MESSAGE_1_TIME = 1
    RESTART_WEBINAR_MESSAGES_TIME = 1
    FIRST_OFFER_MESSAGE_1_TIME = 1
    FIRST_OFFER_MESSAGE_2_TIME = 1
    FIRST_OFFER_MESSAGE_3_TIME = 1
    QUESTION_MESSAGE_2_TIME = 1  # 3 days and 20 hours
    FINAL_OFFER_MESSAGE_1_TIME = 1
    FINAL_OFFER_MESSAGE_2_TIME = 1