from datetime import datetime, time, timedelta
from zoneinfo import ZoneInfo

import main

SUBSCRIPTION_REMINDER_1_TIME  = 5 * 60
SUBSCRIPTION_REMINDER_2_TIME  = 15 * 60
LESSON_MESSAGE_1_AUTO_TIME  = 15 * 60
LESSON_MESSAGE_2_AUTO_TIME  = 15 * 60
LESSON_MESSAGE_3_AUTO_TIME  = 7 * 60
WEBINAR_REMINDER_0_AUTO_TIME  = 5 * 60
WEBINAR_REMINDER_1_AUTO_TIME_FIXED = '23:59'
WEBINAR_REMINDER_3_TIME  = 60 * 2 * 60
WEBINAR_REMINDER_4_TIME  = 60 * 3 * 60
WEBINAR_REMINDER_5_TIME  = 45 * 60
WEBINAR_REMINDER_6_TIME  = 15 * 60
WEBINAR_REMINDER_7_TIME  = 15 * 60
WEBINAR_REMINDER_8_TIME  = 15 * 60
WEBINAR_REMINDER_9_TIME  = 15 * 60
WEBINAR_REMINDER_10_TIME  = (60 + 25) * 60
QUESTION_MESSAGE_1_TIME  = 30 * 60
RESTART_WEBINAR_MESSAGES_TIME  = 60 * 20 * 60
FIRST_OFFER_MESSAGE_1_TIME  = 30 * 60
FIRST_OFFER_MESSAGE_2_TIME  = 60 * 24 * 60
FIRST_OFFER_MESSAGE_3_TIME  = 60  * 23 * 60
QUESTION_MESSAGE_2_TIME  = ((60 * 24 * 4) - (60 * 4)) * 60 # 3 days and 20 hours
FINAL_OFFER_MESSAGE_1_TIME = 60 * 24 * 60
FINAL_OFFER_MESSAGE_2_TIME  = 60 * 20 * 60

FIRST_WEBINAR_TIME = "12:00"
SECOND_WEBINAR_TIME = "19:00"

def test_mode():
    global SUBSCRIPTION_REMINDER_1_TIME
    global SUBSCRIPTION_REMINDER_2_TIME
    global LESSON_MESSAGE_1_AUTO_TIME
    global LESSON_MESSAGE_2_AUTO_TIME
    global LESSON_MESSAGE_3_AUTO_TIME
    global WEBINAR_REMINDER_0_AUTO_TIME
    global WEBINAR_REMINDER_1_AUTO_TIME_FIXED
    global WEBINAR_REMINDER_3_TIME
    global WEBINAR_REMINDER_4_TIME
    global WEBINAR_REMINDER_5_TIME
    global WEBINAR_REMINDER_6_TIME
    global WEBINAR_REMINDER_7_TIME
    global WEBINAR_REMINDER_8_TIME
    global WEBINAR_REMINDER_9_TIME
    global WEBINAR_REMINDER_10_TIME
    global QUESTION_MESSAGE_1_TIME
    global RESTART_WEBINAR_MESSAGES_TIME
    global FIRST_OFFER_MESSAGE_1_TIME
    global FIRST_OFFER_MESSAGE_2_TIME
    global FIRST_OFFER_MESSAGE_3_TIME
    global QUESTION_MESSAGE_2_TIME  # 3 days and 20 hours
    global FINAL_OFFER_MESSAGE_1_TIME
    global FINAL_OFFER_MESSAGE_2_TIME
    global TODAY_2359

    main.TEST_MODE = True

    SUBSCRIPTION_REMINDER_1_TIME = 3
    SUBSCRIPTION_REMINDER_2_TIME = 3
    LESSON_MESSAGE_1_AUTO_TIME = 3
    LESSON_MESSAGE_2_AUTO_TIME = 3
    LESSON_MESSAGE_3_AUTO_TIME = 3
    WEBINAR_REMINDER_0_AUTO_TIME = 3
    WEBINAR_REMINDER_1_AUTO_TIME_FIXED = '23:59'
    WEBINAR_REMINDER_3_TIME = 3
    WEBINAR_REMINDER_4_TIME = 3
    WEBINAR_REMINDER_5_TIME = 3
    WEBINAR_REMINDER_6_TIME = 3
    WEBINAR_REMINDER_7_TIME = 3
    WEBINAR_REMINDER_8_TIME = 3
    WEBINAR_REMINDER_9_TIME = 3
    WEBINAR_REMINDER_10_TIME = 3
    QUESTION_MESSAGE_1_TIME = 3
    RESTART_WEBINAR_MESSAGES_TIME = 3
    FIRST_OFFER_MESSAGE_1_TIME = 3
    FIRST_OFFER_MESSAGE_2_TIME = 3
    FIRST_OFFER_MESSAGE_3_TIME = 3
    QUESTION_MESSAGE_2_TIME = 3
    FINAL_OFFER_MESSAGE_1_TIME = 3
    FINAL_OFFER_MESSAGE_2_TIME = 3
